CREATE OR REPLACE TYPE TYP_VETERINAIRE AS OBJECT
(
  id  NUMBER(2),
  nom VARCHAR2(20)
);
/
CREATE TABLE Espece
(
  nom VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE ClasseEspece (

    nom VARCHAR2(50) PRIMARY KEY

);
/
CREATE OR REPLACE TYPE TYP_MEDICAMENT AS OBJECT
(
  nomMolecule VARCHAR2(20)
);
/
CREATE OR REPLACE TYPE LISTE_MEDICAMENTS AS TABLE OF TYP_MEDICAMENT;
/
CREATE OR REPLACE TYPE TYP_TRAITEMENT AS OBJECT
(
  veterinaire TYP_VETERINAIRE,
  debut       DATE,
  duree       NUMBER(2),
  medicament  LISTE_MEDICAMENTS
)
NESTED TABLE medicament STORE AS liste_med;

CREATE OR REPLACE TYPE LISTE_MEDICAMENTS AS TABLE OF TYP_MEDICAMENT;
/
CREATE OR REPLACE TYPE TYP_ANIMAL AS OBJECT
(
  nom           VARCHAR2(20),
  poids         FLOAT,
  taille        FLOAT,
  dateNaissance DATE,
  espece        TYP_ESPECE,
  traitement    TYP_TRAITEMENT
);
/
CREATE OR REPLACE TYPE LISTE_ANIMAUX AS TABLE OF TYP_ANIMAL;
/
CREATE TABLE CLIENT
(
  nom           VARCHAR2(20) NOT NULL,
  prenom        VARCHAR2(20) NOT NULL,
  dateNaissance DATE         NOT NULL,
  adresse       VARCHAR2(20) NOT NULL,
  numero        VARCHAR2(10) NOT NULL,
  animal        LISTE_ANIMAUX,
  UNIQUE (nom, prenom, dateNaissance),
  CONSTRAINT ck_phone
    CHECK (numero LIKE '[0-9]{10}')
)
NESTED TABLE animal STORE AS liste_animaux;