INSERT INTO CLASSE VALUES('mammifere');
INSERT INTO CLASSE VALUES('reptile');
INSERT INTO CLASSE VALUES('oiseau');

INSERT INTO VETERINAIRE VALUES (TYP_VETERINAIRE(1,'Harry')) ;
INSERT INTO VETERINAIRE VALUES (TYP_VETERINAIRE(2,'Cybil'));
INSERT INTO VETERINAIRE VALUES (TYP_VETERINAIRE(3,'Alessa'));
INSERT INTO VETERINAIRE VALUES (TYP_VETERINAIRE(4,'Michael'));
INSERT INTO VETERINAIRE VALUES (TYP_VETERINAIRE(5,'James'));

INSERT INTO ESPECE VALUES ('chat', TYPE_CLASSE('mammifere'));
INSERT INTO Espece VALUES('chien',TYPE_CLASSE('mammifere'));
INSERT INTO Espece VALUES('anaconda',TYPE_CLASSE('reptile'));
INSERT INTO Espece VALUES('perroquet',TYPE_CLASSE('oiseau'));
INSERT INTO Espece VALUES('vache',TYPE_CLASSE('mammifere'));

