DROP TABLE Animal;
/
DROP TABLE Client;
/
DROP TYPE TYP_CLIENT FORCE;
/
DROP TYPE liste_ref_Animal FORCE;
/
DROP TYPE REF_ANIMAL FORCE;
/
DROP TYPE TYP_ANIMAL FORCE;
/
DROP TYPE TYP_TRAITEMENT FORCE;
/
DROP TYPE COL_PRESCRIPTION FORCE;
/
DROP TYPE TYP_PRESCRIPTION FORCE;
/
DROP TYPE TYP_MEDICAMENT FORCE;
/
DROP TYPE LISTE_REF_TRAITEMENT FORCE;
/
DROP TYPE REF_TRAITEMENT FORCE;
/
DROP TABLE Espece;
/
DROP TABLE ClasseEspece;
/
DROP TYPE TYP_VETERINAIRE FORCE;
/
DROP TYPE TYP_ASSISTANT FORCE;
/
DROP TYPE TYP_CLASSEESPECE FORCE;
/
DROP TYPE LISTE_REF_ESPECE FORCE;
/
DROP TYPE REF_ESPECE FORCE;
/
DROP TYPE TYP_ESPECE FORCE;
/
DROP TABLE Medicament;
/
DROP TABLE Veterinaire;
/
DROP TABLE Assistant;
/
DROP TABLE Traitement;
/
DROP SEQUENCE id_client_seq;
/
DROP SEQUENCE id_vet_seq;
/
DROP SEQUENCE id_assist_seq;
/
DROP SEQUENCE id_traitement_seq;
/